version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  build:
    commands:
      - cd $CODEBUILD_SRC_DIR/ubuntu/standard/2.0
      - docker build -t aws/codebuild/standard:2.0 .
cache:
  paths:
    - /root/.cache/pip/**/*
