version: 0.2

phases:
  install:
    runtime-versions:
      docker: 18
      python: 3.7
  build:
    commands:
      - python3.7 --version
      - aws sts get-caller-identity
      - aws ecr get-login
      - aws ecr describe-repositories --repository-names dnd
#      - python3.7 build.py
cache:
  paths:
    - /root/.cache/pip/**/*
